### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ctigrisht** [Blazored/Modal#157]
On mobile view, the modal is not scrollable, so it will block the ui on the modal

**Comment by chrissainty** [comment]
Hi @ctigrisht, I don't see this as a bug, this is easily configurable with CSS. We've deliberately kept the CSS for the modal as simple as possible to allow people the most flexibility. 

Adding the following class will fix your problem:

```css
.blazored-modal-content {
    overflow-y: scroll
}
```
