### ISSUE TITLE
Override Style

### ISSUE THREAD

**Issue by FraserElectronics** [Blazored/Modal#380]
**Describe the bug**
Following the readme to use a custom style.

**To Reproduce**
1. Override class:
```cs
    private void ShowModal()
    {
        var opts = new ModalOptions()
        {
            Class = "my-modal-class"
        };

        Modal.Show<ItemPicker>( "Pick Item(s) from list", opts );
    }
```
2. Create a custom style in App.css (copied from sample):
```css
.my-modal-class {
    display: flex;
    flex-direction: column;
    width: 60vw;
    height: 60vh;
    background-color: #d43131;
    border-radius: 12px;
    border: 1px solid #968f8f;
    padding: 0.5rem;
    z-index: 102;
    box-shadow: 0 15px 15px rgba(0,0,0,.75);
}
```

3. Display the form.

**Expected behaviour**
Would expect to see a bright Red background (#d43131).

**Screenshots**
None.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly
 - DotNet 6.0
 - Edge Browser

**Additional context**
None.
